<?
error_reporting(0);
require("_headr.php");
if($_SESSION["password"] != $pass || $_SESSION["sessid"] != session_id()) die(logout());
$db_passed = "";
$connection = @mysql_connect($db_server, $db_user, $db_pass) or $connection = false;
if($connection) {
	$db_return = "Connection to database server is working ";
	if(mysql_select_db($db_name, $connection)) {
		$db_passed = TRUE;
	} else {
		$db_return = $db_return + "but could not find the database.";
		$db_passed = FALSE;
	}
} else {
	$db_return = "Connection to database server is not working ";
	$db_passed = FALSE;
}

if($db_passed) {
	$db_return = "<span class=\"good\">".$db_return."</span>";
} else {
	$db_return = "<span class=\"err\">".$db_return."</span>";
}

if($show_empty == 1) {
	$show_empty = "checked=\"checked\"";
}

if($use_rss == 1) {
	$use_rss = "checked=\"checked\"";
}

if($debugging == 1) {
	$debugging = "checked=\"checked\"";
}

if($nice_permalinks == 1) {
	$nice_permalinks = "checked=\"checked\"";
}

$head_path = $root . "head.php";

?>

<p class="title-head">Configuration</p>
	
<form>

  <fieldset>
    <legend>Site</legend>
<p class="btn add" onclick="get_data('get_edit_file',{path:'<? echo $head_path; ?>','type':'head','refreshurl':'show_config'})">Edit index head</p><p class="clear"></p>
<p class="margin"></p>
<input type="text" class="text-input" id="title" value="<? echo htmlspecialchars($title); ?>"/><p class="form-title">&mdash;Title</p><p class="help-ico"></p>
<div class="help-box">What put here will be what the browser window will use as title.</div><p class="clear"></p>

<p class="margin"></p>
<div class="form-obj"><input type="checkbox" id="use_rss" <? echo $use_rss; ?> /><p class="form-title">&mdash;Use RSS</p><p class="help-ico"></p><div class="help-box">If you check this checkbox you will turn on rss, rss is generated by rss-feed.php in the Core folder. If you turn it off, no feed will be generated and you website won't show any links to the feed.</div></div>
<div class="form-obj"><input type="checkbox" id="nice_perma" <? echo $nice_permalinks; ?> /><p class="form-title">&mdash;Nice permalinks</p><p class="help-ico"></p><div class="help-box">With this checked Core will output permalinks in a nice friendly format like "http://www.yoursite.com/23" for accessing the entry with id 23. Without it checked links are in standard format instead "http://www.yoursite.com/?entry=23.<br /><br />Does require rewriting of the url, a htaccess file was supplied with core which will rewrite to the above format.
</div></div>
</fieldset>

<p class="clear"></p>
<p class="margin"></p>


  <fieldset>
<legend>Core</legend>
<input type="text" class="text-input" id="user" value="<? echo $user; ?>" /><p class="form-title">&mdash;User</p><p class="help-ico"></p><div class="help-box">Whatever username you want to use. This serves no purpose other than to connect your password with a specific name. If you change this, make sure to input your existing or a new password in the field below.</div><p class="clear"></p>
<input type="password" id="pass" class="text-input" /><p class="form-title">&mdash;Pass</p><p class="help-ico"></p><div class="help-box">The password you want to use for logging in.</div><p class="clear"></p>
<p class="margin"></p>
<select id="theme">
<?
$thms = search_folder($root . "themes");
echo "<option value=\"$theme\">$theme</option>";
foreach($thms as $t) {
	if($t != $theme) echo "<option value=\"$t\">$t</option>";
}

?>
</select><p class="form-title">&mdash;Theme</p><p class="help-ico"></p><div class="help-box">This should be the name of the folder you want to use as theme.</div>


<p class="clear"></p>


<p class="margin"></p>

<div class="form-obj"><input type="checkbox" id="show_empty" <? echo $show_empty; ?> /><p class="form-title">&mdash;Show Empty</p><p class="help-ico"></p><div class="help-box">If you check this, entries without any media will also be shown, if you plan on using images/video/sound in every entry made there is no need to check this.</div></div>
<div class="form-obj"><input type="checkbox" id="debugging" <? echo $debugging; ?> /><p class="form-title">&mdash;Debug</p><p class="help-ico"></p><div class="help-box">With this check you will use debugging while using the admin panel, this is great if you are experiencing something wierd that you either want to report as a bug or solve yourself.</div></div>


</fieldset>
<p class="clear"></p>
<p class="margin"></p>



<fieldset>
<legend>Database</legend>
<input type="text" class="text-input" id="db_user" value="<? echo $db_user; ?>" /><p class="form-title">&mdash;Database user</p><p class="help-ico"></p><div class="help-box">The username you use for connections with your database server, this is often found at you host online configuration.</div><p class="clear"></p>
<input type="password" class="text-input" id="db_pass" value="(hidden)" /><p class="form-title">&mdash;Database pass</p><p class="help-ico"></p><div class="help-box">The password used to connect to the database server, check your hosts online configuration for this if you don't know what it is.</div><p class="clear"></p>
<input type="text" class="text-input" id="db_name" value="<? echo $db_name; ?>" /><p class="form-title">&mdash;Database name</p><p class="help-ico"></p><div class="help-box">The name of the database, this is not the server, or a specific database table, but the database itself.</div><p class="clear"></p>
<input type="text" class="text-input" id="db_server" value="<? echo $db_server; ?>" /><p class="form-title">&mdash;Database server</p><p class="help-ico"></p><div class="help-box">The server where your database can be found. For some people it works just putting "localhost" in this field (without the quotes).</div><p class="clear"></p><br /><br />
<? echo $db_return; ?>

</fieldset>

</form>
<p class="margin"></p>
<p class="btn submit" onclick="submit_form('edit_config','show_config')">Submit configuration</p>