<script type="text/javascript">

$(document).ajaxStart(function(){
	$("#core-loader").show();
});

$(document).ajaxSuccess(function(){
	$("#core-loader").fadeOut();
});

<? LOAD_TAGS("JAVASCRIPT"); ?>

$.tagArray = tags; // tags is a variable generated by LOAD_TAGS("JAVASCRIPT");

$(".tag-all").click(function(){
$.tagAll();
});


//Config
$.contentTarget = $("#load-content"); // into which element you want to load new content
$.firstLoad("<? echo $first_load; ?>");
$.historyInit($.sendRequest);

var http = "<? echo $http; ?>";
$("a").click(function(){
	var hash = this.href;
	if(hash.indexOf("#") > 0); hash = hash.replace(http,'');
	if(hash.charAt(0)=="#") {
		hash = hash.replace(/^.*#/, '');
		$.historyLoad(hash);
		return false;
	}
});

</script> 